[package]
name = "itg-buddy-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
colored = "2.1.0"
confy = "0.6.1"
poise = "0.6.1"
serde = "1.0.210"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
